import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';

test('round tests all words once, then groups can be practiced, edited and undone', async () => {
  const html=await readFile(new URL('../dist/index.html',import.meta.url),'utf8');
  const dom=new JSDOM(html,{url:'https://ting.test'});
  const spoken=[];
  const voice={voiceURI:'mandarin',name:'Tingting',lang:'zh-CN',localService:true};
  dom.window.speechSynthesis={cancel(){},getVoices:()=>[voice],addEventListener(){},speak:utterance=>spoken.push(utterance)};
  globalThis.window=dom.window;
  globalThis.document=dom.window.document;
  globalThis.localStorage=dom.window.localStorage;
  globalThis.SpeechSynthesisUtterance=class {constructor(text){this.text=text}};
  const $=selector=>document.querySelector(selector);
  const click=selector=>$(selector).click();
  const button=text=>[...document.querySelectorAll('.stage button')].find(b=>b.textContent===text);
  const group=title=>[...document.querySelectorAll('.group')].find(g=>g.querySelector('h3').textContent.startsWith(title));
  const errors=[];dom.window.addEventListener('error',event=>errors.push(event.error));
  try {
    await import('../dist/app.js?study-flow');
    $('#words').value='冬天|dōng tiān\n夏天|xià tiān\n春天|chūn tiān';$('#words').oninput();
    click('#start');
    assert.equal($('#visual').textContent,'');
    assert.equal($('.hidden-word').getAttribute('aria-label'),'Word hidden');
    assert.equal($('.hidden-word').children.length,5,'listening indicator draws five voice bars');
    assert.equal(spoken.at(-1).text,'冬天');
    assert.equal($('#memorized').hidden,true);
    assert.equal($('#previous').disabled,true);
    click('#reveal');
    assert.equal($('.hanzi').textContent,'冬天');
    click('#memorized');
    assert.equal($('#counter').textContent,'1 of 3 tested · 1 remembered · 0 need review');
    click('#previous');
    assert.equal($('#counter').textContent,'0 of 3 tested · 0 remembered · 0 need review');
    assert.equal(spoken.at(-1).text,'冬天');
    click('#reveal');click('#memorized');
    click('#next');
    assert.equal(spoken.at(-1).text,'春天');
    click('#reveal');click('#memorized');
    assert.match($('.stage').textContent,/Round complete/);
    assert.match(group('Needs review').textContent,/夏天/);
    assert.match(group('Remembered').textContent,/冬天.*春天/);
    group('Remembered').querySelector('li button').click();
    assert.match(group('Needs review').textContent,/冬天/);
    group('Needs review').querySelector('.next').click();
    assert.equal($('#counter').textContent,'0 of 2 tested · 0 remembered · 0 need review');
    click('#reveal');click('#memorized');click('#reveal');click('#memorized');
    assert.equal(group('Needs review').querySelectorAll('li button').length,0);
    button('Previous word').click();
    assert.equal($('#counter').textContent,'1 of 2 tested · 1 remembered · 0 need review');
    click('#back');
    assert.match($('#savedProgress').textContent,/2 remembered · 1 need review/);
    assert.equal($('#openRemembered').textContent,'Remembered · 2');
    click('#openRemembered');
    assert.match($('.stage h2').textContent,/Your words/);
    assert.match(group('Remembered').textContent,/冬天/);
    assert.equal($('#counter').textContent,'2 remembered · 1 need review');
    group('Needs review').querySelector('.next').click();
    assert.equal($('#counter').textContent,'0 of 1 tested · 0 remembered · 0 need review');
    click('#groups');
    assert.match(group('Needs review').textContent,/夏天/);
    click('#back');
    click('[data-mode="pinyin"]');click('#start');click('#start');
    assert.equal($('.hanzi').textContent,'冬天');
    assert.equal($('#reveal').hidden,true);
    $('#answer').value='dong4 tian1';click('#check');
    assert.equal($('#memorized').hidden,true);
    click('#next');
    assert.equal($('.hanzi').textContent,'夏天');
    $('#answer').value='xia4 tian1';click('#check');click('#memorized');
    $('#answer').value='chun1 tian1';click('#check');click('#memorized');
    assert.match(group('Needs review').textContent,/冬天/);
    click('#back');
    assert.match($('#savedProgress').textContent,/2 remembered · 1 need review/);
    assert.match($('.playback-hint').textContent,/try a few times/);
    assert.deepEqual(errors,[]);
  } finally {
    dom.window.close();
    for(const key of ['window','document','localStorage','SpeechSynthesisUtterance'])delete globalThis[key];
  }
});

test('only the checked words are studied, and pinyin edits keep the unchecked ones', async () => {
  const html=await readFile(new URL('../dist/index.html',import.meta.url),'utf8');
  const dom=new JSDOM(html,{url:'https://ting.test'});
  const spoken=[];
  const voice={voiceURI:'mandarin',name:'Tingting',lang:'zh-CN',localService:true};
  dom.window.speechSynthesis={cancel(){},getVoices:()=>[voice],addEventListener(){},speak:utterance=>spoken.push(utterance)};
  globalThis.window=dom.window;
  globalThis.document=dom.window.document;
  globalThis.localStorage=dom.window.localStorage;
  globalThis.SpeechSynthesisUtterance=class {constructor(text){this.text=text}};
  const $=selector=>document.querySelector(selector);
  const click=selector=>$(selector).click();
  const pick=hanzi=>[...document.querySelectorAll('.pick')].find(label=>label.textContent.startsWith(hanzi)).querySelector('input');
  const toggle=hanzi=>{const box=pick(hanzi);box.checked=!box.checked;box.onchange()};
  const errors=[];dom.window.addEventListener('error',event=>errors.push(event.error));
  try {
    await import('../dist/app.js?picker');
    $('#words').value='冬天|dōng tiān\n夏天|xià tiān\n春天|chūn tiān';$('#words').oninput();
    assert.equal($('#picker').hidden,false);
    assert.equal(document.querySelectorAll('.pick input:checked').length,3);
    toggle('夏天');
    assert.match($('#pickCount').textContent,/2 of 3 selected/);
    click('#start');
    assert.equal($('#counter').textContent,'0 of 2 tested · 0 remembered · 0 need review');
    click('#reveal');click('#memorized');
    assert.equal(spoken.at(-1).text,'春天');
    click('#back');
    assert.equal(pick('夏天').checked,false,'the choice survives a round');
    click('#pickNone');click('#start');
    assert.equal($('#setupError').textContent,'Select at least one word to study.');
    click('#pickAll');toggle('冬天');
    click('[data-mode="pinyin"]');click('#start');
    assert.equal(document.querySelectorAll('.review-row').length,2);
    document.querySelectorAll('.review-row')[0].children[1].value='xià tian';
    click('#start');
    assert.equal($('#words').value,'冬天|dōng tiān\n夏天|xià tian\n春天|chūn tiān');
    assert.equal($('.hanzi').textContent,'夏天');
    assert.deepEqual(errors,[]);
  } finally {
    dom.window.close();
    for(const key of ['window','document','localStorage','SpeechSynthesisUtterance'])delete globalThis[key];
  }
});
